---
title: "Muller Report Analysis"
author: "Moises Evangelista"
date: "Prepared `r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    fig_crop: no
    toc: true
    toc_depth: 2
subtitle: Report Validation
fontsize: 11pt
header-includes:
- \usepackage{palatino}
- \renewcommand{\familydefault}{\sfdefault}
- \fontfamily{ppl}\selectfont

- \usepackage{xcolor}
- \usepackage[normalem]{ulem}
- \hypersetup{colorlinks,urlcolor=blue, linkcolor=black}
- \usepackage{float}
- \PassOptionsToPackage{obeyspaces}{url}
- \usepackage{graphicx, array, blindtext, longtable, tikz}
- \usepackage[export]{adjustbox}

---


\makeatletter 
\begingroup \lccode`+=32 \lowercase
 {\endgroup \def\Url@ObeySp{\Url@Edit\Url@String{ }{+}}}
 \def\Url@space{\penalty\Url@sppen\ }
\makeatother

```{r setup, include=FALSE}

# the latex code above is to keep spaces in file paths

knitr::opts_chunk$set(cache = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE,
                      #dpi = 500
                      dev = "cairo_pdf")

rm(list = ls()) #start with empty workspace

# setwd("~/GitHub/MullerReportAnalysis") # set the working directory

# list.files()
library(tidyverse)
library(magick)

library(pdftools)

options(scipen = 999)

```

# The Mueller Report, officially titled Report on the Investigation into Russian Interference in the 2016 Presidential Election

```{r getData}

# read pdf file
# break it into pages
# ocr each page
# get pic of all 400+ pages
# do text analysis
# https://www.justice.gov/storage/report.pdf
# 
```


```{r get_pageImages, echo = FALSE, eval=FALSE}

rm(list = ls()) #start with empty workspace

startTime <- Sys.time()

download.file("https://www.justice.gov/storage/report.pdf",
              destfile = "report.pdf"
              ,mode = "wb"
              ,quiet = FALSE)

# get pdf info

info <- pdf_info("report.pdf")

# count number of pages in pdf file

numberOfPageInPdf <- info[2] %>%
  unlist( use.names = FALSE)

Sys.time() - startTime # Time difference of 2.665368 mins

# create location to store pics

ifelse(!dir.exists(file.path("./pics")),dir.create(file.path("./pics")), FALSE)

startTime <- Sys.time()

all_tables <- vector("list", length = numberOfPageInPdf )

# loop for to save each page and get text info

for (i in seq_along(1:numberOfPageInPdf)) {
  
  timeDiff <- Sys.time() - startTime 
  
  print(paste(i, "of", numberOfPageInPdf
              ,as.double(timeDiff) %>% signif(5),
              units(timeDiff)))
  
  x <- image_read_pdf("report.pdf",
                      ,pages = i) %>% 
    image_reducenoise(.) %>% 
    image_despeckle()
  
  # error handling - skips to next URL if it gets an error
  result <- try(
    all_tables[[i]] <- x %>% 
      image_ocr() %>%
      as.data.frame()
    
  ); if(class(result) == "try-error") next;
  
  try(x %>% 
        image_scale(., "400") %>% #resize proportionally to width: 400px
        image_write(., path = paste0("./pics", "/pg_", i,".png")))
  
}

Sys.time() - startTime # Time difference of 1.745381 hours

rpt_text <- all_tables %>% # head(1000) %>%
  plyr::ldply(data.frame) 

rm(list = setdiff(ls(), c("rpt_text"
                          ,"numberOfPageInPdf")))

save.image(file = "rpt_text.Rdata")

```

```{r createPictWithAllpages, eval = FALSE}

rm(list = ls()) #start with empty workspace

load("rpt_text.Rdata") 

divisors <- function(x){
  # https://stackoverflow.com/questions/19465720/writing-a-function-to-calculate-divisors-in-r
  #  Vector of numberes to test against
  y <- seq_len(x)
  #  Modulo division. If remainder is 0 that number is a divisor of x so return it
  y[ x%%y == 0 ]
}

divisors(numberOfPageInPdf)

numberOfPageInPdf/14

# 32 pages long by 14 wide

# read page 1 then page 15 then page 15+15+1, ...
# read page 2 then page 16 then page 15+15+1, ...

pgs_toPop <- matrix(1:numberOfPageInPdf
                    , nrow = 20
                    , byrow = TRUE)   %>%  # fill matrix row-wise
  as_tibble()


# remove previous files

list.files(recursive = TRUE, pattern = "column") %>%
  unlink

startTime <- Sys.time()

for(i in names(pgs_toPop)){
  
  print(paste("column", i)) 
  #  df[[paste(i, 'length', sep="_")]] <- str_length(df[[i]])
  
  pages <- pgs_toPop %>% select(i) %>% as.vector() %>% unlist(use.names = FALSE)
  
  for (j in seq_along(1:length(pages))) {
    
    print(paste("page", j))
    
    x <- image_read( paste0("./pics"
                            , "/pg_"
                            , pages[j]
                            ,".png")) %>% 
      image_border("black", "1x1")
    
    if(j == 1) {
      img1 <- x 
    }
    else {
      img1 <- img1 %>% c(x)
    }
    
  }
  
  img1 <- img1 %>% image_append( stack = TRUE) %>% 
    image_scale(., "400") %>% #resize proportionally to width: 400px
    image_write( path = paste0("./pics", "/column_", i,".png"))
  
}

print(Sys.time() - startTime) # Time difference of 59.08112 secs

startTime <- Sys.time()

colpages <- list.files(recursive = TRUE, pattern = "column")

for (j in seq_along(1:length(colpages))) {
  
  print(paste("page", j))
  
  x <- image_read( colpages[j]) %>% 
    image_scale(., "400") %>% #resize proportionally to width: 200px
    # image_despeckle(., times = 2)
    image_contrast(., sharpen = 1)
  
  if(j == 1) {
    img1 <- x
  }
  else {
    img1 <- img1 %>% c(x)
  }
  
  img1 <- img1 %>%
    image_append( stack = FALSE)
} 

img1 %>% 
  image_write( path = paste0("./pics", "/all_cols.png"))

print(Sys.time() - startTime) # Time difference of 2.88814 mins

```


```{r readFinalPicPlot, eval = TRUE, warning=FALSE, message = FALSE, include = TRUE, fig.width=4}

all_cols <- image_read( "pics/all_cols.png") %>% 
  image_scale(., "500")
# 
# library(grid)
# 
# Cairo::CairoPDF(file = "plotAllPages.pdf"
#                 #units = "in", dpi = 150,
#                 ,width = 15,
#                 height = 12,
#                 pointsize = 10)
# 
# ggplot() +
#   theme_void() +
#   annotation_custom(
#     grob = ggplotGrob(grid.raster(all_cols)),
#     xmin = 0,
#     xmax = 3,
#     ymin = 5,
#     ymax = 10
#   ) 

fig <- image_graph(width = 500, height = 562, res = 96)

ggplot() +
  theme_void()
dev.off()

# Combine
out <- image_composite(fig, all_cols)
print(out)

```


```{r textAnalysis_tokens1, eval = TRUE}

rm(list = ls()) #start with empty workspace

load("rpt_text.Rdata") 

library(readtext)
library(tidytext)

library(textstem)
library(qdapDictionaries)

data(action.verbs)

acntVersbs <- action.verbs

# library(udpipe)

startTime <- Sys.time()

pdfText <- readtext("report.pdf")

Sys.time() - startTime # Time difference of 29.90652 secs

nrc_joy <- get_sentiments("nrc") 

text_words <- pdfText %>%
  unnest_tokens(word, text)
  
  actvVerbs <- text_words %>% 
  mutate(acntVerb  = grepl(acntVersbs %>%
                             paste0("^", ., "$", collapse = "|")
                           , word)) %>% 
  filter(acntVerb == TRUE) %>% 
  count(word)

sntimet <- text_words %>% 
  inner_join(nrc_joy)
  
text_bigrams <- rpt_text %>%
  select(text = 1) %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  separate(bigram, c("A", "B"), " ", extra = "merge") %>% 
  filter(!A %in% stop_words$word) %>% 
  filter(!B %in% stop_words$word) %>%
  filter(grepl("[A-z]", A)) %>% 
  filter(grepl("[A-z]", B)) %>% 
  # mutate_at(vars(A, B),
  #           list(~gsub("\\s+", " ",.))) %>% 
  mutate_at(vars(A, B),
            list(~trimws(toupper(.)))) %>% 
  # inner_join(verbs %>% 
  #              select(B = token)) %>% 
  count(A, B, sort = TRUE) %>% 
  filter(n >=30)

library(igraph)

g <- text_bigrams %>% 
  graph_from_data_frame(., directed=T) 

E(g)$weight = text_bigrams$n


```

```{r plotNetworkVerbs, include = TRUE}

plot(g
     ,edge.arrow.size = .2
     ,edge.curved = 0
     ,vertex.label = V(g)$names
     ,vertex.color = "orange"
     ,vertex.frame.color="#555555"
     ,vertex.size = 5 #as.matrix(node.size)
     ,vertex.label = V(g)$names
     ,vertex.label.color = "black",
     vertex.label.cex = .3) 
# 
# RColorBrewer::display.brewer.all( n = 10
#                                   , exact.n = FALSE) # display palettes
# 
# getPalette = grDevices::colorRampPalette(RColorBrewer::brewer.pal(
#   length (unique(text_bigrams$CurrentStep))
#   , "Paired"))
# 
# colrs <- getPalette(length (unique(text_bigrams$CurrentStep))) %>% 
#   sub("#F8F18F", "#4d4d4d",.)
# 
# V(g)$name
# 
# V(g)$color <- colrs
# 
# edge.start <- ends(g, es=E(g), names=F)[,1]
# 
# edge.col <- V(g)$color[edge.start]
# 
# plot(g
#      ,layout=layout.circle
#      #,vertex.label.color = adjustcolor(V(g)$color, alpha.f = 0.99)
#      ,edge.arrow.size = scales::rescale(E(g)$weight, to=c(.5,5))  
#      #,edge.arrow.size = log( E(g)$weight) /3# 0.2
#      ,vertex.label.cex = 0.70
#      ,main = ""
#      ,edge.curved =.1
#      ,edge.color =  adjustcolor(edge.col, alpha.f = 0.5)
#      ,edge.width = 5# scales::rescale(E(g)$weight, to=c(.5, 10))    #log( E(g)$weight) # 5, #log(E(g)$width),
#      # edge.color =  adjustcolor(V(g)$color, alpha.f = 1),
#      ,vertex.color = adjustcolor(V(g)$color, alpha.f = 0.5),
#      vertex.size = 5)




```